### ISSUE TITLE
Giuhub 이슈 발생 / Git pull request - can't automatically merge 발생

### ISSUE THREAD

**Issue by Hwannni** [Hwannni/Study_Algorithms#61]
## Github 사용 도중 `Git pull request - can't automatically merge` 이 발생
![image](https://github.com/Hwannni/Study_Algorithms/assets/97112678/f51ae5ae-8488-46ee-92f0-82abadf5a5c9)

pull requests 하는 과정 중 위 이미지와 같은 문제가 발생했어.
발생 원인으로는 minchur의 커밋을 pull 하지 않고 내 코드를 commit 하는 바람에 생긴 문제로 보여.
어떻게 해결하면 좋을까?

**Comment by jiminchur** [comment]
### 롤백해서 다시 돌리는 방법 한번 해보세요!!
* 이전 commit 내용 확인
```
git reflog
```

* 명령어 + commit id로 선택한 시점 이후의 commit 취소
```
git reset [commit id]
```

* github에 반영
```
git push -f
```

**Comment by Hwannni** [comment]
### 롤백은 성공! 근데 더 큰 문제 발생...
- 의견 반영해서 여차저차 롤백은 했는데 pull requests를 누르다 main과 minan 브랜치에 지금까지 작업했던 폴더와 파일들이 전부 삭제됨
- minchur의 깃허브로 들어가서 브랜치들을 확인해보니까 다행히 minchur 깃허브엔 자료들이 남아 있는걸 확인
- 회고록을 보니까 일부 데이터는 롤백된 것으로 보여
![image](https://github.com/Hwannni/Study_Algorithms/assets/97112678/1584a544-d2b0-4a77-a34c-e23ab7de131b)
![image](https://github.com/Hwannni/Study_Algorithms/assets/97112678/be9bed86-6ffa-4e48-ae61-275b1ba926a6)

**Comment by jiminchur** [comment]
### 아직 제 레퍼지토리 main branch에는 파일들이 남아 있으니깐 git clone으로 파일 백업해둔 후에 다시 commit 할게요!!
* git clone으로 파일 백업하기
![스크린샷 2024-07-03 오후 11 59 02](https://github.com/Hwannni/Study_Algorithms/assets/145955453/1611da24-1b06-4cd5-a5c2-b68fbe3b14cc)
* main , minchur branch update하기
* 파일 옮겨서 다시 Pull request 하기
    * #54 

### 해결 완료!!
